### ISSUE TITLE
`onClickOutside` and `onEscapeKey` doesn't update callbacks

### ISSUE THREAD

**Issue by makarov906** [theKashey/react-focus-on#17]
Hello @theKashey,

I have realised that `onClickOutside` and `onEscapeKey` doesn't update callbacks. 
I did some research, and I think it because `useEffect` in `Effect.tsx` doesn't get deps for update those funcs ([here](https://github.com/theKashey/react-focus-on/blob/a6a3281c74aa0d2c0dea9aef49abaf982dd4cc9a/src/Effect.tsx#L92))

Or maybe there is another way to do this?

**Comment by theKashey** [comment]
I've drafter PR with the possible fix for this issue, but it would take some time to actually test it.

**Comment by theKashey** [comment]
Released as `3.1.1` __beta__, as long as I haven't found time to test it in isolation, so gonna test in some external projects first, before removing a beta flag.
Join the club.
