### ISSUE TITLE
removeScrollBar not exposed from react-remove-scroll

### ISSUE THREAD

**Issue by AndrewBrough** [theKashey/react-focus-on#18]
I'd love to be able to remove the scroll bar but can't seem to access this prop. Would be nice to have it available!

Awesome package, does basically everything I need aside from this.

**Comment by AndrewBrough** [comment]
I can say the same about gapMode - I'd actually like to not have a gap, but it's enabled by default.

**Comment by theKashey** [comment]
I would recommend to import `react-remove-scroll` directly for now - reexporting it _thought_ FocusLock might harm tree shaking (for the double imports case, aka sidecar, to be more concrete).

And `gap` have to be "reserved", or content on the page would jump, both changing width and height (as long as more "wider" text would consume less vertical space).

If you need something to be "100%" width - there are extra classNames exposed from `remove-scroll` to control this moment.
