### ISSUE TITLE
Feature request: add possibility to pass other props to react-focus-lock and react-scroll-locky components

### ISSUE THREAD

**Issue by smashercosmo** [theKashey/react-focus-on#2]
Currently in my app I need to pass persistentFocus prop to react-focus-lock and noRelative prop to react-scroll-locky. Would it be possible to add either these extra props or possibility to pass all react-focus-lock and react-scroll-locky props?

**Comment by theKashey** [comment]
Not a problem. The only question - why you need especially these props? They both are a bit _odd_.

**Comment by smashercosmo** [comment]
Yes, you're right) After playing with it a bit more I came to conclusion, that I don't really need them)

**Comment by smashercosmo** [comment]
Thx for sowing the seeds of doubt in me) And for awesome package)

**Comment by theKashey** [comment]
Meanwhile - I am thinking about swapping `scroll-lock` with `remove-scroll`. The second one is smaller, friendly to portals, but does not prevent `click`s outside of a lock - it could prevent only event bubbling, hence you will have to "drop a shadow" behind modal/lock.

It is ok for you?
