### ISSUE TITLE
Console log leftover

### ISSUE THREAD

**Issue by peduarte** [theKashey/react-focus-on#22]
Hey,

I just noticed there's a [console.log](https://github.com/theKashey/react-focus-on/blob/master/src/Combination.tsx#L8) here.

Want me to remove it?

Cheers!

**Comment by theKashey** [comment]
You are welcome :)

**Comment by benoitgrelard** [comment]
I've already submitted a PR for that ;)

**Comment by peduarte** [comment]
🔥

**Comment by theKashey** [comment]
Fixed in 3.1.3
