### ISSUE TITLE
Activation lifecycle bugs introduced in #19

### ISSUE THREAD

**Issue by benoitgrelard** [theKashey/react-focus-on#24]
Hi @theKashey 

Since #19 got merged and `3.1.1` got released, the activation lifecycle is not working properly.
I haven't managed to specifically find out why, but he's a simple reproduction:

#### react-focus-on 3.1.0
Working activation lifecycle
https://codesandbox.io/s/react-focus-on-310-wg4js

#### react-focus-on 3.1.1
Activation lifecycle not working correctly
https://codesandbox.io/s/react-focus-on-311-3rz2r

---
Both examples are exactly the same, only the version of `react-focus-on` differs.
Pay attention to the logs:
- in 3.1.0 when opening you get `activated`, and when closing you get `deactivated`
- in 3.1.1 when opening you get `deactivated` and `activated`, and when closing you get nothing

This is a breaking issue for us and I believe we should rollback that PR (#19) until we can figure out a way to incorporate the intended fix (#17) without breaking the lifecycle.

Let me know what you think!

✌️

**Comment by theKashey** [comment]
Yeah, hooks are not always great...

**Comment by theKashey** [comment]
Fixed

**Comment by benoitgrelard** [comment]
Works great, thanks!

**Comment by theKashey** [comment]
You are welcome.
