### ISSUE TITLE
Unable to activate links or submit forms within FocusOn

### ISSUE THREAD

**Issue by jimmynotjim** [theKashey/react-focus-on#3]
I have modals that contain links and forms (with some custom validation) that stopped working when I added FocusOn to them. Digging deeper, it appears this `onClick` listener that's passed to focus-lock is the culprit https://github.com/theKashey/react-focus-on/blob/master/src/component.tsx#L33. Unfortunately removing it causes any clicks within the modal to trigger a the `onClickOutside` callback. 

Any tips for moving forward without having to add custom click handlers to everything?

**Comment by theKashey** [comment]
You did everything right. I am just going to fix it.
Not a big deal - it's already working _right_ for scroll events, I just need to replicate the same logic here.

**Comment by jimmynotjim** [comment]
Dang! Fastest response on an OSS project I've ever had. Thanks so much, you give me a point to strive for with my own projects. Let me know if there's anything I can help with, including testing any fixes.

**Comment by theKashey** [comment]
You just created the issue at the right time :) And quite severe to be honest.

**Comment by theKashey** [comment]
react-focus-on@2.0.1
