### ISSUE TITLE
Tabbing in radio buttons are broken in FocusOn

### ISSUE THREAD

**Issue by sebpettersson** [theKashey/react-focus-on#35]
When using a radio button group inside FocusOn, keyboard tabbing is broken. When the focus is on a radio button the focus get "stuck" and doesn't move to the next element when pressing tab.

In the test case below, when the focus trap is enabled:

* When the first radio button has focus, tabbing doesn't do anything. Shift + tab works and the focus is set to the button.

* When the second radio button has focus, tabbing doesn't do anything. Shift + tab doesn't work either.

* When the last radio button has focus, tabbing and shift + tab both work as expected.

Compare it to the second example with checkboxes which work correctly.

[Test case](https://codesandbox.io/s/peaceful-mcnulty-44skd)

**Comment by theKashey** [comment]
Yeah, there is a special logic for radio buttons (they are a bit special), which is probably got broken a bit.

**Comment by theKashey** [comment]
Related https://github.com/theKashey/react-focus-lock/issues/103

**Comment by theKashey** [comment]
Fixed in v3.4.1
