### ISSUE TITLE
Keydown event incorrectly triggered on children

### ISSUE THREAD

**Issue by narehart** [theKashey/react-focus-on#36]
If an `onKeyDown` handler causes `FocusOn` to render and the first focusable element has an `onKeyUp` or `onClick` handler, that handler will also be called.

Reproduced here: https://codesandbox.io/s/wizardly-vaughan-2y8in
Doesn't happen when focusing using refs: https://codesandbox.io/s/naughty-curie-kmmu8

**Comment by theKashey** [comment]
The funny thing - it's working that way only for `Enter`, not for `Space`.

**Comment by narehart** [comment]
Maybe that's because of the way React handles `onClick` handlers. They are also triggered by the `Enter` key. My guess is this uses the `keyup` event under the hood. So I think what's happening here is the `onKeyDown` opens `FocusOn` which moves focus to the `button` and then when the key is released the `onClick` or `onKeyUp` event is fired which both use `keyup`.

**Comment by narehart** [comment]
If I defer rendering of the `onFocus` to the end of the event loop it doesn't trigger the `onClick` handler: https://codesandbox.io/s/divine-flower-jq4rn

**Comment by theKashey** [comment]
Let me create issue for React then. It shall not be solved here.
