### ISSUE TITLE
Allow ability to disable specific functionality

### ISSUE THREAD

**Issue by davwheat** [theKashey/react-focus-on#39]
In one of our components, we have a prop which allows you to be able to disable/enable scrolling while it's open. We'd like to keep this available for backwards compatibility.

What I propose is a prop like `disableScrollLock` to achieve this.

**Comment by theKashey** [comment]
Try `scrollLock={false}` prop, which is already supported by `FocusOn` - https://github.com/theKashey/react-focus-on/blob/master/src/UI.tsx#L19

Sorry - it's not documented in the Readme, however _documented_ in types - https://github.com/theKashey/react-focus-on/blob/master/src/types.ts#L27

**Comment by davwheat** [comment]
Brilliant! Thanks for your help :)
