### ISSUE TITLE
Change repository description

### ISSUE THREAD

**Issue by joecritch** [theKashey/react-focus-on#40]
Currently, the repository description is `The final solution for WAI ARIA compatible modal dialogs or full-screen tasks.`. Without going into the details, the term "final solution" has a terrible connotation.

May I suggest changing this to something like "the ultimate solution"?

**Comment by theKashey** [comment]
`🎯 Solution for WAI ARIA compatible modal dialogs or full-screen tasks, you were looking for` ?
