### ISSUE TITLE
as={Component} not exposed from react-focus-lock

### ISSUE THREAD

**Issue by AaronPowell96** [theKashey/react-focus-on#42]
I am trying to use react-focus-on with the as= prop to render my own nav without it being nested inside a div. As seen here: 
![image](https://user-images.githubusercontent.com/17838632/86368313-f328ff80-bc74-11ea-85bb-d1fdf91bc123.png)
however, it doesnt seem to be exposed from react-focus-lock.

EDIT: Have done a little digging and it seems internally the as is being used as RemoveScroll, and RemoveScroll is using a div, maybe we could pass through the as prop to removeScroll and that renders the component if provided?

Ive tried to use and implement forwardProps and that removed the div but then the lock didnt work.

**Comment by theKashey** [comment]
That's theoretically possible, but is it actually needed? Could you please explain your use case?
For example, why Focus Lock you not be outside `nav` (as per screenshot), or inside `nav` - why it should be nav?

> And not working `forwardProps` is definitely an issue.

**Comment by AaronPowell96** [comment]
Hey, sorry for the late reply, the reason was for semantics, I didn't think a nav should be inside a div. With a screenreader it never picked up the navigation when it was inside a div, but when you have the header with a nav it did.

**Comment by theKashey** [comment]
>  I didn't think a nav should be inside a div

But could https://caninclude.glitch.me/can/include/?child=nav&parent=div

Anyway, I've got you

**Comment by AaronPowell96** [comment]
Thank you, will be interested to see the solution as I did spend a few hours looking around haha

**Comment by theKashey** [comment]
Shipped as a part of v3.5.0
