### ISSUE TITLE
Allow `style` prop on <FocusOn />

### ISSUE THREAD

**Issue by thompsongl** [theKashey/react-focus-on#46]
Similar to how `className` is applied, `style` could be applied to the main `div` (the one with the `data-focus-lock-disabled` attribute).

Happy to open a pull request, but wanted to ask your preference:

1) Allow `style` prop only.
2) Allow `lockProps` prop similar to `react-focus-lock` where any valid HTML or React attribute can be applied.

After switching to `react-focus-on` from `react-focus-lock` this has been the only API gap. Thanks for your work!

**Comment by theKashey** [comment]
Valid point. A good addition to #42
