### ISSUE TITLE
Use with react-transition-group doesn't clear aria-hidden attributes

### ISSUE THREAD

**Issue by qasimalyas** [theKashey/react-focus-on#48]
I have an implementation where I'm using react-focus-on with react-transition-group. The idea is that as I transition in some JSX I lock focus to the area I need. The initial load is fine but when the section is closed but clicking outside or escape key, the elements that were hidden still have the aria-hidden attributes as well the button having `pointer-events: none`.

https://codesandbox.io/s/dry-wind-4h4tt?file=/src/App.js 

Is there a way to undo the aria-hidden attributes that were set? Or perhaps a suggestion on a different approach?

**Comment by theKashey** [comment]
add `unmountOnExit` 😉  https://codesandbox.io/s/condescending-lamport-ev1zj?file=/src/App.js

**Comment by qasimalyas** [comment]
Thanks, I should've re-read the docs again. Works perfectly now 🙂
