### ISSUE TITLE
React-focus-lock dependency

### ISSUE THREAD

**Issue by jonnystening** [theKashey/react-focus-on#50]
Any chance react-focus-on's react-focus-lock dependency will be bumped?

I really need the https://github.com/theKashey/react-focus-lock/issues/108 (`tabindex="-1"`) fix

I'm getting `react-focus-lock@2.3.1` but need `react-focus-lock@2.4.0`

Thanks in advance!

**Comment by timoisalive** [comment]
We actually just hit this issue as well, so +1 for bumping the dependency!

**Comment by theKashey** [comment]
All deps have been bumped in 3.5.2 to the latest versions.
