### ISSUE TITLE
Update aria-hidden to v. 1.1.3 to fix an IE11 incompatibility issue

### ISSUE THREAD

**Issue by viheikki** [theKashey/react-focus-on#51]
Please update the aria-hidden dependency version to 1.1.3 as the previous versions on IE11 will crash if the DOM tree contains e.g. SVGElement(s). 

Please note, the update will fix the crash, but won't fix aria-hidden to function perfectly on IE11.

**Comment by theKashey** [comment]
Better later than never - released among `3.5.4`
