### ISSUE TITLE
Can't resolve tslib

### ISSUE THREAD

**Issue by chawes13** [theKashey/react-focus-on#52]
After running `npm install` on a project with dependencies on multiple major versions of `tslib` (i.e., ^1.0.0 and ^2.0.0), I'm getting the following error:

```
ERROR in: ./node_modules/react-focus-on/dist/es2015/Combination.js
Module not found: Error: Can't resolve 'tslib' in '<path>/node_modules/react-focus-on/dist/es2015' 
```

Should `tslib` be declared as a dependency?

**Comment by theKashey** [comment]
fixed in 3.5.3
