### ISSUE TITLE
Shadow DOM

### ISSUE THREAD

**Issue by eirslett-visma** [theKashey/react-focus-on#58]
Would it be possible to have a new version of this library, with the latest versions of its dependencies? Looks like react-focus-lock recently got support, and it would be awesome to have it in react-focus-on as well!

**Comment by theKashey** [comment]
Pending:
- https://github.com/theKashey/react-remove-scroll/issues/59
- https://github.com/theKashey/react-remove-scroll/issues/45 (you probably need this as well)

**Comment by theKashey** [comment]
react-focus-on@3.6.0 should fix the majority of shadow dom related problems, however still not all.
