### ISSUE TITLE
How to preventDefault?

### ISSUE THREAD

**Issue by TwisterMc** [theKashey/react-focus-on#59]
I have FocusOn up and running. When I click outside of the focused area, it's running `onClickOutside` and also clicking on the item in the background. Typically I'd just add something like `e.preventDefault();` but that's not working. How do I get it to close FocusOn, but not also click something in the background?

**Comment by theKashey** [comment]
There are two ways:
- preventDefault `onClickOutside={(e) => { e.preventDefault(); somethingElse()}}`
- keep stuff locked for a moment `onClickOutside={(e) => { setTimeout(somethingElse)}}`

**Comment by theKashey** [comment]
The other possible way is to use some "shadow" element (it can be a pseudo element) 'consuming' clicks. So you will not be able to click on something you should not be able to click.

**Comment by TwisterMc** [comment]
Well, I guess I was doing something stupid as it works now. Thanks!
