### ISSUE TITLE
Heading, paragraph text are not selectable inside `FocusOn`

### ISSUE THREAD

**Issue by yathomasi** [theKashey/react-focus-on#60]
With the addition of `react-focus-on`, we got this strange behavior of not being able to select any text inside the `FocusOn` component. 
- I don't see conflicting CSS like `user-select`. `pointer-events` is set to `auto` but that shouldn't stop text-selection

I couldn't figure out what caused the issue. What could be the reason?

**Comment by theKashey** [comment]
This is a known behavior of "focus locking" as selected text belongs to the `body`, which is not in the focus.
It is controlled via `persistentFocus` property (https://github.com/theKashey/react-focus-lock/blob/master/interfaces.d.ts#L41 ) and expected to be disabled by default.
Checked random example with pure FocusOn (Chrome and Safari) and I can select any text.

**Comment by yathomasi** [comment]
Needed to set the child div with `tabIndex= {0}` or  set [`focusLock: false`](https://github.com/theKashey/react-focus-on/blob/master/src/UI.tsx#L20). I would be very interested to know the reason behind this if you have an explanation 🙏 .

**Comment by theKashey** [comment]
Ok. So here is the problem - if `Modal` is not _focusable_ (does not have `tabindex`) - then the focus might bubble to the other parent, which might be focusable.
This is why selection  _might_ bubble up to body  and focus lock will know how to handle it.

Take this example - https://codesandbox.io/s/good-react-example-modal-dialog-forked-k4imc?file=/src/App.js and:
- "watch" `document.activeElement`
- open a modal and select a text
- remove `tabIndex` and repeat

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/582410/163660391-1adf7259-be85-4099-b1e8-139c987ebe16.png">

- wrap modal with another div with tabindex
```tsx
 <div tabindex={-1}>
        {modal}
 </div>
```
- see your very issue
