### ISSUE TITLE
`gapMode` prop/API is not actually used

### ISSUE THREAD

**Issue by cee-chen** [theKashey/react-focus-on#65]
Despite being documented in the main README, setting `gapMode="padding"` as a prop does not appear to correctly change the CSS applied to the page `body` to set `padding-right` instead of `margin-right` (which the underlying [react-remove-scroll-bar library implies it should](https://github.com/theKashey/react-remove-scroll-bar/blob/master/src/component.tsx#L42)).

[`gapMode` usage appears to be nonexistent](https://github.com/search?q=repo%3AtheKashey%2Freact-focus-on%20gapMode&type=code), and its [original implementation](https://github.com/theKashey/react-focus-on/commit/0298cc8) no longer exists in the codebase.

Demo of broken behavior: https://codesandbox.io/s/romantic-jennings-tv3l31?file=/demo.js:397-444

Notice that even with `gapMode="padding"` passed, when the focus lock is open, the CSS rendered is still using margin-right:

<img width="1149" alt="" src="https://user-images.githubusercontent.com/549407/225371649-08772133-5d9d-4667-b2ea-eb2c63bd09ea.png">

A bit more context:

Our team could really use support for this, as unfortunately one of our major consumers has `width: 100%; min-width: 100%` CSS set on their body, which causes `margin-right` to not work as expected. We don't really have standing to tell them to remove this CSS, so the only other alternative to use `padding-right` instead (which works correctly with 100% width).

As a workaround we're currently grabbing the `--removed-body-scroll-bar-size` CSS var and manually setting `padding-right`, but we'd love to be able to remove this workaround.

**Comment by theKashey** [comment]
Hey, thank you for the bug report. v3.8.0 has been released with a fix

**Comment by cee-chen** [comment]
Holy cow, that was so fast!! Thanks a million @theKashey, you rock :)

**Comment by cee-chen** [comment]
Gah actually, sorry to be annoying, but I'm not sure this is working. I updated the above CodeSandbox link to use 3.8.0 and gapMode is still not working as expected, and instead there's a React error in the DOM which appears to imply that `gapMode` is being passed to the underlying DOM element:

<img width="881" alt="" src="https://user-images.githubusercontent.com/549407/225708018-4da62e2b-f651-4e2f-9757-37cc9ec0d6ca.png">

**Comment by theKashey** [comment]
😭 because problem is now on ReactRemoveScroll side. I need to update relationships between focus-on(supports) -> remove-scroll(🤡) -> remove-scroll-bar(supports).

Works on local due some unpublished updates. I need to develop more reality-related test suites

**Comment by Haraldson** [comment]
@theKashey Hey! Any progress on the peer dependency to react-remove-scroll, and getting that up to speed?

**Comment by theKashey** [comment]
🫠 time flies. Sorry, too much other stuff fighting for priorities.

**Comment by theKashey** [comment]
`3.8.1` seems to handle the problem accordingly.

There could be some _glitches_ in the scrollbar if one uses `gapMode=padding` to be addressed at https://github.com/theKashey/react-remove-scroll-bar/pull/36
