### ISSUE TITLE
Missing Prop `noFocusGuards`

### ISSUE THREAD

**Issue by RaidenDilan** [theKashey/react-focus-on#68]
Hi, I'm using this library and so far it's been working great but unfortunately I need `noFocusGuards` prop which is currently not exposed.

Happy to open a pull request, but I wanted to ask your preference:

Allow `noFocusGuards` prop only.

**Comment by theKashey** [comment]
Your contribution will be very appreciated 🙏, especially if you can share your example requiring this very rarely required prop.

**Comment by RaidenDilan** [comment]
So my usage is quite simple, I'd like to keep my HTML clean and semantic which is why I need to set `noFocusGuards` on. That way it would not be required for me to change any existing styling in my app to count for the extra divs. And I'm aware that the extra guards are there for virtual inputs which secure tab index.

**Comment by RaidenDilan** [comment]
Do you have any special requirements as to how you want pull requests to be opened or do I just create a branch from master and just open the pull request?

**Comment by RaidenDilan** [comment]
P.S. When I try to push my branch to remote repo, I get `ERROR: Permission to theKashey/react-focus-on.git denied to RaidenDilan`. Perhaps I need access to your repo.

**Comment by theKashey** [comment]
You are expected to `Fork` the repo and commit change to your version. Then you can open PR from your version to the upstream.

This way GitHub and the community can be assured that no unexpected change will ever be committed to the main branch, and branch protection rules were added years after this practice got established.
