### ISSUE TITLE
iOS: keyboard popping up on input focus scrolls locked body

### ISSUE THREAD

**Issue by andrew--r** [theKashey/react-focus-on#69]
Hi!

I use react-focus-on in my app for implementing proper modal dialogs. Discovered an issue on iOS: when dialog contains a long form and user clicks on input, Safari puts focus on it, pops up keyboard and shifts viewport up so that the input stays in the viewport above the keyboard. The problem is that locked document scroll is also affected by this behaviour. I’ve set up a [reproduction sandbox](https://h65qgh.csb.app) and made a recording demonstrating the issue: 

https://github.com/theKashey/react-remove-scroll/assets/2734841/0557bade-9a22-433b-8150-67eae1973da0

By the end of the recording you can see the bottom of the page. Is it possible to prevent document scroll in this case?

**Comment by theKashey** [comment]
There is no real way to prevent body scroll. `focus-lock` is trying to _stop a cause_ for it, but if it happens - it happens.
The only solution I know, but am a little hesitant to implement at the generic library level - save `scrollTop` on modal open and restore on modal close.
