### ISSUE TITLE
Adding support for `react-focus-lock` `crossFrame` prop

### ISSUE THREAD

**Issue by cee-chen** [theKashey/react-focus-on#72]
Hey again @theKashey! 👋 We just got a question about iframe behavior from one of our consumers. While I was looking for a solution or workaround, I noticed that `react-focus-lock` [supports a `crossFrame` prop](https://github.com/theKashey/react-focus-lock/blob/2eed9ca683fd71f581638ea7dc44177436f0d3ab/interfaces.d.ts#L43-L49) that was added a few years ago (https://github.com/theKashey/react-focus-lock/issues/104) and would likely be exactly what we need.

Is there any chance we could extend `FocusOn` to allow the same `crossFrame` configuration and pass that to `FocusLock`? 🙏 That would be incredibly helpful to us. Would you accept a PR with this addition?

**Comment by cee-chen** [comment]
Thanks again for looking at this so quickly @theKashey! I know you're busy, but any chance you could drop a quick mention in this thread once the new feature has been released to npm? 🙏

**Comment by theKashey** [comment]
Better late than never 😅 `3.9.0` has been released.
