### ISSUE TITLE
Warnings after upgrading to v3.0.0

### ISSUE THREAD

**Issue by smashercosmo** [theKashey/react-focus-on#8]
Started getting the following warnings after upgrading:
```
Warning: Unknown event handler property `onActivation`. It will be ignored.
```
```
Warning: Unknown event handler property `onDeactivation`. It will be ignored.
```

**Comment by theKashey** [comment]
Thank you for reporting this issue. I've found a little time bomb with hooks and will release a new version tomorrow.

The real problem behind this issue - `aria-hidden` is not being set, while scroll-lock and focus-lock are working as they would.
All units are working perfectly, but the integration part failed :(

**Comment by smashercosmo** [comment]
Thank you. Waiting for the new release then)

**Comment by theKashey** [comment]
Done. This time I've got a test for it :)
