### ISSUE TITLE
Prevent focus removal for external resources

### ISSUE THREAD

**Issue by aronlg** [theKashey/react-focus-on#80]
Hi,

How can I prevent `pointer-events: none` being applied to external resources(non React elements)?

Example:
I have a sticky chat button loaded via Google tag manager. It renders outside root. Is there a way to apply it to `shards` somehow? or even better, prevent adding `pointer-events: none` to anything outside `#root` when `<FocusOn>` is enabled?

**Comment by theKashey** [comment]
Probably the best solution is to extend `shouldIgnore` to `aria-hidden`, the one applying `pointer-events:none`
Simultaneously make focus-lock ignore `aria-hidden` elements.

That would be a good continuation of a joint efforts of different pieces this solution is composed from.
