### ISSUE TITLE
Error in production after upgrading to v3.0.1

### ISSUE THREAD

**Issue by makarov906** [theKashey/react-focus-on#9]
After upgrading i get the following error in production mode
```
Error: Sidecar medium not found
```

**Comment by theKashey** [comment]
:(  yesterday was a quite strange day.

**Comment by theKashey** [comment]
Trying to reproduce the issue, and can't do it.

**Comment by andrew--r** [comment]
Error is reproducible only after production webpack build (dev mode is ok) and when using full import (`import {FocusOn} from 'react-focus-on';`)

**Comment by theKashey** [comment]
I was not able to break it from inside `focus-on`, but when I used it as a package at third party side - 🔥
Now I could fix it!

**Comment by theKashey** [comment]
The problem was with tree shaking of `react-remove-scroll`, which was caused by a bug in webpack (yet to report).

I've update `sideEffects` for said package to include `sidecar`, and that's fixed the problem.

Should be ok now :)

**Comment by makarov906** [comment]
Thank you for a quick fix :)

**Comment by theKashey** [comment]
Thank you for beta testing :)
